# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  deploy_job:
     name: deploy_job
     runs-on: ubuntu-latest
     steps:
       - name: run_deploy
         uses: JamesIves/github-pages-deploy-action@master
         env:
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }
           BRANCH: gh-pages
           BUILD_SCRIPT: npm run deploy
           
           
